version: "3.7"

services:
  databaseSozei:
    image: postgres
    container_name: databaseSozei
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sozei
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-network

  app:
    build: .
    container_name: sozei
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - databaseSozei
    depends_on:
      - databaseSozei
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: "bridge"
