version: "3.7"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sozei
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-network

  app:
    build: .
    container_name: sozei
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge
